#!/bin/bash
###

if [[ "$(wc -l <$(sentinal lint))" -gt 0 ]]; then
  OUTPUT=$(cat $(sentinal lint) | xargs npm run lint) || {
    block  "You MUST fix the following lint errors, even if you think they are unrelated to your changes:\n$OUTPUT"
  }
fi