<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Bifrost.Domain\Bifrost.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="9.33.0" />
    <PackageReference Include="WolverineFx" Version="6.36.0" />
    <PackageReference Include="WolverineFx.Http" Version="6.36.0" />
    <PackageReference Include="WolverineFx.Http.Marten" Version="6.36.0" />
    <PackageReference Include="WolverineFx.Marten" Version="6.36.0" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.36.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>
</Project>
