packages:
  - "packages/*"
  - "examples/*"

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9

catalog:
  "@types/node": ^25.6.2
  "@types/ws": ^8.18.1
  "@typescript/native-preview": latest
  bumpp: ^11.1.0
  typescript: ^6.0.3
  vite-plus: ^0.2.0
  vitest-gwt: ^4.1.0
  ws: ^8.18.3

allowBuilds:
  "@google/genai": set this to true or false
  protobufjs: set this to true or false
